language: php

php:
  - 7.4
  - 7.3
  - 7.2
  - 7.1
  - 7.0

env:
  - XHGUI_SAVE_HANDLER=mongodb
  - XHGUI_SAVE_HANDLER=pdo XHGUI_PDO_DSN="mysql:host=localhost;dbname=xhgui" XHGUI_PDO_USER=root
  - XHGUI_SAVE_HANDLER=pdo XHGUI_PDO_DSN="sqlite:/tmp/xhgui.sqlite3"
  - XHGUI_SAVE_HANDLER=pdo XHGUI_PDO_DSN="pgsql:dbname=xhgui user=postgres password="

jobs:
  allow_failures:
    - php: 7.4
    # Allow pdo jobs to fail. Env match must be exact
    # https://docs.travis-ci.com/user/build-matrix/#excluding-jobs-with-env-value
    - env: XHGUI_SAVE_HANDLER=pdo XHGUI_PDO_DSN="mysql:host=localhost;dbname=xhgui" XHGUI_PDO_USER=root
    - env: XHGUI_SAVE_HANDLER=pdo XHGUI_PDO_DSN="sqlite:/tmp/xhgui.sqlite3"
    - env: XHGUI_SAVE_HANDLER=pdo XHGUI_PDO_DSN="pgsql:dbname=xhgui user=postgres password="
  include:
    - php: 7.2
      env: COVERAGE=1

services:
  - mongodb
  - mysql
  - postgresql

cache:
  directories:
    - $HOME/.composer/cache

install:
  - .travis/install.sh

script:
  - .travis/run.sh
